// Local seed data + Excel staff import list.
// Staff data extracted from: Nursing License & CPD Tracking Sheet.xlsx
window.CPD_SEED_USERS = [
  {
    "id": "local-admin",
    "username": "d.milhem",
    "password": "1234",
    "role": "admin",
    "active": true,
    "fullName": "Diya Omar M. Milhem",
    "department": "Nursing Administration",
    "area": "Admin",
    "dhpLicense": "",
    "dhpExpiry": "",
    "category1": 40,
    "category23": 45,
    "email": "d.milhem@westbaymedicare.com",
    "mobile": "+974 66852603",
    "notes": ""
  },
  {
    "username": "h.siman",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Honeylore Siman",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2018-07-08",
    "dhpLicense": "N4269",
    "qid": "46",
    "dhpExpiry": "2026-04-30",
    "category1": 49.25,
    "category23": 41.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 1; Staff ID: 46"
  },
  {
    "username": "l.ciriaco",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Luvill Ciriaco",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2018-07-08",
    "dhpLicense": "N4704",
    "qid": "47",
    "dhpExpiry": "2026-09-30",
    "category1": 32.75,
    "category23": 10.75,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 2; Staff ID: 47"
  },
  {
    "username": "g.palisoc",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Glenda Palisoc",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2018-07-15",
    "dhpLicense": "N4162",
    "qid": "54",
    "dhpExpiry": "2026-04-03",
    "category1": 40.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 3; Staff ID: 54"
  },
  {
    "username": "m.basilio",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "May Basilio",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2018-10-01",
    "dhpLicense": "N5773",
    "qid": "76",
    "dhpExpiry": "2026-06-30",
    "category1": 44.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 4; Staff ID: 76"
  },
  {
    "username": "i.edralin",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ivy Edralin",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2018-09-30",
    "dhpLicense": "N7557",
    "qid": "101",
    "dhpExpiry": "2028-02-28",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 5; Staff ID: 101"
  },
  {
    "username": "a.velasquez",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Adriene Joy Velasquez",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2019-10-06",
    "dhpLicense": "N22255",
    "qid": "192",
    "dhpExpiry": "2028-04-23",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 6; Staff ID: 192"
  },
  {
    "username": "r.guillermo",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Rejoy Guillermo",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2020-03-03",
    "dhpLicense": "N5120",
    "qid": "212",
    "dhpExpiry": null,
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 7; Staff ID: 212"
  },
  {
    "username": "m.oppus",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "May Oppus",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2020-06-16",
    "dhpLicense": "N5969",
    "qid": "230",
    "dhpExpiry": "2026-09-30",
    "category1": 41.25,
    "category23": 9.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 8; Staff ID: 230"
  },
  {
    "username": "r.guillermo2",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Rejoyce Guillermo",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2020-07-26",
    "dhpLicense": "N5038",
    "qid": "235",
    "dhpExpiry": "2027-01-14",
    "category1": 21.25,
    "category23": 9.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 9; Staff ID: 235"
  },
  {
    "username": "d.rose",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Deepa Rose",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2020-09-20",
    "dhpLicense": "N28928",
    "qid": "246",
    "dhpExpiry": "2027-02-21",
    "category1": 23.25,
    "category23": 8.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 10; Staff ID: 246"
  },
  {
    "username": "t.tom",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Teslin TOM",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2020-10-11",
    "dhpLicense": "N27522",
    "qid": "247",
    "dhpExpiry": "2026-12-31",
    "category1": 31.5,
    "category23": 37.75,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 11; Staff ID: 247"
  },
  {
    "username": "c.montes",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Cheryl Montes",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2020-10-19",
    "dhpLicense": "N7604",
    "qid": "249",
    "dhpExpiry": "2028-02-28",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 12; Staff ID: 249"
  },
  {
    "username": "m.cabrera",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Marie Grace CABRERA",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2020-11-15",
    "dhpLicense": "N16835",
    "qid": "257",
    "dhpExpiry": "2028-02-27",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 13; Staff ID: 257"
  },
  {
    "username": "k.ramirez",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Kiara Ramirez",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2020-11-22",
    "dhpLicense": "N21675",
    "qid": "259",
    "dhpExpiry": "2026-05-17",
    "category1": 42.0,
    "category23": 44.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 14; Staff ID: 259"
  },
  {
    "username": "k.englis",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Karen Mae Englis",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2020-12-12",
    "dhpLicense": "N24796",
    "qid": "264",
    "dhpExpiry": "2027-03-12",
    "category1": 12.0,
    "category23": 10.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 15; Staff ID: 264"
  },
  {
    "username": "m.marcellana",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Mishell MARCELLANA",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2020-12-26",
    "dhpLicense": "N7931",
    "qid": "266",
    "dhpExpiry": "2026-12-10",
    "category1": 41.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 16; Staff ID: 266"
  },
  {
    "username": "a.mangawang",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Agnes  Mangawang",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2021-02-21",
    "dhpLicense": "N5730",
    "qid": "280",
    "dhpExpiry": "2026-06-30",
    "category1": 31.5,
    "category23": 23.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 17; Staff ID: 280"
  },
  {
    "username": "e.sali",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Elaine A. Sali",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2021-03-14",
    "dhpLicense": "N3525",
    "qid": "286",
    "dhpExpiry": "2026-04-30",
    "category1": 40.75,
    "category23": 40.75,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 18; Staff ID: 286"
  },
  {
    "username": "m.papio",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Mary Klaudine Papio",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2021-05-17",
    "dhpLicense": "N6061",
    "qid": "291",
    "dhpExpiry": "2026-10-31",
    "category1": 40.5,
    "category23": 40.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 19; Staff ID: 291"
  },
  {
    "username": "m.nicolas",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "May Angela Nicolas",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2021-06-22",
    "dhpLicense": "N26137",
    "qid": "305",
    "dhpExpiry": "2026-07-23",
    "category1": 45.75,
    "category23": 30.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 20; Staff ID: 305"
  },
  {
    "username": "m.soriano",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Maria Soriano",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2021-08-01",
    "dhpLicense": "N4406",
    "qid": "311",
    "dhpExpiry": "2026-05-31",
    "category1": 40.0,
    "category23": 46.75,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 21; Staff ID: 311"
  },
  {
    "username": "v.ambat",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Veranica Ambat",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2021-08-01",
    "dhpLicense": "N1323",
    "qid": "312",
    "dhpExpiry": "2026-07-31",
    "category1": 43.75,
    "category23": 40.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 22; Staff ID: 312"
  },
  {
    "username": "a.abion",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ambrielle Abion",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2021-11-02",
    "dhpLicense": "N4083",
    "qid": "342",
    "dhpExpiry": "2028-03-13",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 23; Staff ID: 342"
  },
  {
    "username": "d.porquerino",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Diana Porquerino",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2021-12-07",
    "dhpLicense": "N18288",
    "qid": "356",
    "dhpExpiry": "2026-04-06",
    "category1": 40.0,
    "category23": 21.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 24; Staff ID: 356"
  },
  {
    "username": "a.casio",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Angelie Casio",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2022-01-10",
    "dhpLicense": "N25354",
    "qid": "363",
    "dhpExpiry": "2026-04-16",
    "category1": 40.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 25; Staff ID: 363"
  },
  {
    "username": "j.joseph",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Jissa Ann Joseph",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2022-02-01",
    "dhpLicense": "N23091",
    "qid": "369",
    "dhpExpiry": "2026-09-24",
    "category1": 40.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 26; Staff ID: 369"
  },
  {
    "username": "j.james",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Jasana James",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2020-03-01",
    "dhpLicense": "N5120",
    "qid": "370",
    "dhpExpiry": "2026-07-11",
    "category1": 16.75,
    "category23": 35.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 27; Staff ID: 370"
  },
  {
    "username": "l.tubon",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Lady Rosepink Tubon",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2022-05-17",
    "dhpLicense": "N17128",
    "qid": "389",
    "dhpExpiry": "2027-01-26",
    "category1": 29.0,
    "category23": 11.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 28; Staff ID: 389"
  },
  {
    "username": "n.jose",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Neethu Jose",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2022-05-22",
    "dhpLicense": "N16679",
    "qid": "383",
    "dhpExpiry": "2028-04-28",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 29; Staff ID: 383"
  },
  {
    "username": "s.naiju",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Sarika Naiju",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2022-10-04",
    "dhpLicense": "N16616",
    "qid": "404",
    "dhpExpiry": "2026-11-20",
    "category1": 39.5,
    "category23": 11.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 30; Staff ID: 404"
  },
  {
    "username": "n.jhons",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Nittu Jhons",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2022-11-27",
    "dhpLicense": "N31048",
    "qid": "411",
    "dhpExpiry": "2026-05-25",
    "category1": 41.5,
    "category23": 43.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 31; Staff ID: 411"
  },
  {
    "username": "a.pilaparambath",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Anjuna Pilaparambath",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2023-01-01",
    "dhpLicense": "N31424",
    "qid": "415",
    "dhpExpiry": "2026-03-07",
    "category1": 40.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 32; Staff ID: 415"
  },
  {
    "username": "a.mary",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ajisha Mary",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2023-01-07",
    "dhpLicense": "N32737",
    "qid": "416",
    "dhpExpiry": "2027-01-09",
    "category1": 22.5,
    "category23": 6.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 33; Staff ID: 416"
  },
  {
    "username": "c.byenconsejo",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Cheanne Byenconsejo",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2023-02-01",
    "dhpLicense": "N23995",
    "qid": "420",
    "dhpExpiry": "2026-11-11",
    "category1": 44.5,
    "category23": 41.25,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 34; Staff ID: 420"
  },
  {
    "username": "e.perez",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Emelita Manuel Perez",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2023-05-15",
    "dhpLicense": "N976",
    "qid": "452",
    "dhpExpiry": "2027-02-01",
    "category1": 10.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 35; Staff ID: 452"
  },
  {
    "username": "m.barles",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Mae Penelope Barles",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2023-11-27",
    "dhpLicense": "N36185",
    "qid": "486",
    "dhpExpiry": null,
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 36; Staff ID: 486"
  },
  {
    "username": "j.marcos",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Jasmin Romero Marcos",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2023-11-29",
    "dhpLicense": "N22083",
    "qid": "487",
    "dhpExpiry": "2026-11-05",
    "category1": 50.5,
    "category23": 40.57,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 37; Staff ID: 487"
  },
  {
    "username": "a.gana",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Arlyn Gana",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2024-06-03",
    "dhpLicense": "N28608",
    "qid": "513",
    "dhpExpiry": null,
    "category1": 6.5,
    "category23": 9.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 38; Staff ID: 513"
  },
  {
    "username": "w.reales",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Wilma Reales",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2024-12-04",
    "dhpLicense": "N3015",
    "qid": "542",
    "dhpExpiry": "2027-10-12",
    "category1": 21.5,
    "category23": 3.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 39; Staff ID: 542"
  },
  {
    "username": "j.paz",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Jimmylyn De La Paz",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2025-01-15",
    "dhpLicense": "N16566",
    "qid": "549",
    "dhpExpiry": "2027-02-14",
    "category1": 34.75,
    "category23": 34.75,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 40; Staff ID: 549"
  },
  {
    "username": "b.varghese",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Bincy Varghese",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2025-07-20",
    "dhpLicense": "N22143",
    "qid": "572",
    "dhpExpiry": "2027-07-17",
    "category1": 12.0,
    "category23": 20.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 41; Staff ID: 572"
  },
  {
    "username": "a.taher",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Abdel Rahman Taher",
    "department": "Nursing Department",
    "area": "OR",
    "assignedDoctor": "",
    "joiningDate": "2026-02-08",
    "dhpLicense": "TN143328",
    "qid": "594",
    "dhpExpiry": "2026-08-05",
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 42; Staff ID: 594"
  },
  {
    "username": "m.brisones",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Millie Anne David Brisones",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2026-02-21",
    "dhpLicense": "N35149",
    "qid": "597",
    "dhpExpiry": "2027-11-16",
    "category1": 22.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 43; Staff ID: 597"
  },
  {
    "username": "a.thomas",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Alphonsa Thomas",
    "department": "Nursing Department",
    "area": "OPD",
    "assignedDoctor": "",
    "joiningDate": "2026-03-08",
    "dhpLicense": "N32608",
    "qid": "602",
    "dhpExpiry": "2026-12-21",
    "category1": 20.0,
    "category23": 2.25,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 44; Staff ID: 602"
  },
  {
    "username": "l.guzman",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Liberty Guzman",
    "department": "Nursing Department",
    "area": "CSSD",
    "assignedDoctor": "",
    "joiningDate": "2023-04-16",
    "dhpLicense": "",
    "qid": "440",
    "dhpExpiry": null,
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 45; Staff ID: 440"
  },
  {
    "username": "a.acob",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Arabella Acob",
    "department": "Nursing Department",
    "area": "CSSD",
    "assignedDoctor": "",
    "joiningDate": "2023-07-12",
    "dhpLicense": "",
    "qid": "461",
    "dhpExpiry": null,
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 46; Staff ID: 461"
  },
  {
    "username": "v.centeno",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Vener Centeno",
    "department": "Nursing Department",
    "area": "CSSD",
    "assignedDoctor": "",
    "joiningDate": "2025-02-23",
    "dhpLicense": "TA134809",
    "qid": "555",
    "dhpExpiry": null,
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 47; Staff ID: 555"
  },
  {
    "username": "a.najjar",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ahmad Al Najjar",
    "department": "Nursing Department",
    "area": "OR",
    "assignedDoctor": "",
    "joiningDate": "2018-07-08",
    "dhpLicense": "N9710",
    "qid": "50",
    "dhpExpiry": null,
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 48; Staff ID: 50"
  },
  {
    "username": "a.santos",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Aleha Santos",
    "department": "Nursing Department",
    "area": "OR",
    "assignedDoctor": "",
    "joiningDate": "2019-03-03",
    "dhpLicense": "N2836",
    "qid": "150",
    "dhpExpiry": "2026-10-31",
    "category1": 36.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 49; Staff ID: 150"
  },
  {
    "username": "e.castro",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Editha Castro",
    "department": "Nursing Department",
    "area": "OR",
    "assignedDoctor": "",
    "joiningDate": "2018-10-14",
    "dhpLicense": "N107",
    "qid": "105",
    "dhpExpiry": "2027-01-31",
    "category1": 43.0,
    "category23": 41.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 50; Staff ID: 105"
  },
  {
    "username": "e.benson",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Efua Benson",
    "department": "Nursing Department",
    "area": "OR",
    "assignedDoctor": "",
    "joiningDate": "2018-07-08",
    "dhpLicense": "N23402",
    "qid": "42",
    "dhpExpiry": "2026-08-15",
    "category1": 40.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 51; Staff ID: 42"
  },
  {
    "username": "f.micheal",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Felora Micheal",
    "department": "Nursing Department",
    "area": "OR",
    "assignedDoctor": "",
    "joiningDate": "2019-11-13",
    "dhpLicense": "N15395",
    "qid": "201",
    "dhpExpiry": "2026-07-17",
    "category1": 40.75,
    "category23": 41.75,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 52; Staff ID: 201"
  },
  {
    "username": "j.gadia",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Jeffrey Gadia",
    "department": "Nursing Department",
    "area": "OR",
    "assignedDoctor": "",
    "joiningDate": "2018-07-15",
    "dhpLicense": "N23950",
    "qid": "52",
    "dhpExpiry": null,
    "category1": 24.5,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 53; Staff ID: 52"
  },
  {
    "username": "c.mariam",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Christy Mariam",
    "department": "Nursing Department",
    "area": "OR",
    "assignedDoctor": "",
    "joiningDate": "2022-05-22",
    "dhpLicense": "N32423",
    "qid": "382",
    "dhpExpiry": "2026-11-23",
    "category1": 40.0,
    "category23": 9.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 54; Staff ID: 382"
  },
  {
    "username": "a.balo",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Alfred Balo",
    "department": "Nursing Department",
    "area": "OR",
    "assignedDoctor": "",
    "joiningDate": "2023-06-18",
    "dhpLicense": "N27847",
    "qid": "455",
    "dhpExpiry": "2027-06-13",
    "category1": 39.25,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 55; Staff ID: 455"
  },
  {
    "username": "r.agunat",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Rueben Agunat",
    "department": "Nursing Department",
    "area": "OR",
    "assignedDoctor": "",
    "joiningDate": "2018-07-08",
    "dhpLicense": "N23856",
    "qid": "48",
    "dhpExpiry": "2026-10-25",
    "category1": 33.0,
    "category23": 41.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 56; Staff ID: 48"
  },
  {
    "username": "b.george",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Bilga George",
    "department": "Nursing Department",
    "area": "OR",
    "assignedDoctor": "",
    "joiningDate": "2025-07-01",
    "dhpLicense": "TN137711",
    "qid": "569",
    "dhpExpiry": "2027-10-14",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 57; Staff ID: 569"
  },
  {
    "username": "a.sapii",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Arweda Sapii",
    "department": "Nursing Department",
    "area": "Day Ward",
    "assignedDoctor": "",
    "joiningDate": "2020-11-01",
    "dhpLicense": "N17952",
    "qid": "255",
    "dhpExpiry": "2026-04-30",
    "category1": 33.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 58; Staff ID: 255"
  },
  {
    "username": "v.aranez",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Virna Aranez",
    "department": "Nursing Department",
    "area": "Day Ward",
    "assignedDoctor": "",
    "joiningDate": "2022-04-02",
    "dhpLicense": "N31096",
    "qid": "378",
    "dhpExpiry": "2026-05-30",
    "category1": 45.0,
    "category23": 60.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 59; Staff ID: 378"
  },
  {
    "username": "m.cuyno",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ma. Katrina Cuyno",
    "department": "Nursing Department",
    "area": "Day Ward",
    "assignedDoctor": "",
    "joiningDate": "2022-11-01",
    "dhpLicense": "N23135",
    "qid": "405",
    "dhpExpiry": "2026-11-03",
    "category1": 27.5,
    "category23": 20.7,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 60; Staff ID: 405"
  },
  {
    "username": "f.casareno",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "FE Casareno",
    "department": "Nursing Department",
    "area": "Day Ward",
    "assignedDoctor": "",
    "joiningDate": "2023-02-01",
    "dhpLicense": "N32892",
    "qid": "421",
    "dhpExpiry": "2027-01-30",
    "category1": 45.75,
    "category23": 17.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 61; Staff ID: 421"
  },
  {
    "username": "r.baby",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ruby Baby",
    "department": "Nursing Department",
    "area": "Day Ward",
    "assignedDoctor": "",
    "joiningDate": "2025-06-01",
    "dhpLicense": "TN137446",
    "qid": "564",
    "dhpExpiry": "2027-07-22",
    "category1": 32.0,
    "category23": 9.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 62; Staff ID: 564"
  },
  {
    "username": "a.meethal",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Aswathi Kollacheri Meethal",
    "department": "Nursing Department",
    "area": "Day Ward",
    "assignedDoctor": "",
    "joiningDate": "2026-03-09",
    "dhpLicense": "TN143793",
    "qid": "603",
    "dhpExpiry": null,
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 63; Staff ID: 603"
  },
  {
    "username": "m.escobar",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Marian Escobar",
    "department": "Nursing Department",
    "area": "Dental",
    "assignedDoctor": "",
    "joiningDate": "2018-10-31",
    "dhpLicense": "A2591",
    "qid": "122",
    "dhpExpiry": "2026-12-13",
    "category1": 23.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 64; Staff ID: 122"
  },
  {
    "username": "c.fabito",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Cherrielyn Fabito",
    "department": "Nursing Department",
    "area": "Dental",
    "assignedDoctor": "",
    "joiningDate": "2018-10-01",
    "dhpLicense": "N19632",
    "qid": "95",
    "dhpExpiry": "2026-11-14",
    "category1": 25.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 65; Staff ID: 95"
  },
  {
    "username": "k.andal",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Kevin Andal",
    "department": "Nursing Department",
    "area": "Dental",
    "assignedDoctor": "",
    "joiningDate": "2018-10-14",
    "dhpLicense": "N24530",
    "qid": "108",
    "dhpExpiry": "2027-01-16",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 66; Staff ID: 108"
  },
  {
    "username": "c.sabandal",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Chona Sabandal",
    "department": "Nursing Department",
    "area": "Dental",
    "assignedDoctor": "",
    "joiningDate": "2019-02-02",
    "dhpLicense": "N3275",
    "qid": "155",
    "dhpExpiry": "2026-08-19",
    "category1": 9.5,
    "category23": 46.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 67; Staff ID: 155"
  },
  {
    "username": "a.nocete",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Annaliza Nocete",
    "department": "Nursing Department",
    "area": "Dental",
    "assignedDoctor": "",
    "joiningDate": "2021-08-01",
    "dhpLicense": "N4925",
    "qid": "310",
    "dhpExpiry": "2026-11-30",
    "category1": 28.0,
    "category23": 6.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 68; Staff ID: 310"
  },
  {
    "username": "m.echon",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Michelle Echon",
    "department": "Nursing Department",
    "area": "Dental",
    "assignedDoctor": "",
    "joiningDate": "2024-02-20",
    "dhpLicense": "A22523",
    "qid": "497",
    "dhpExpiry": "2028-01-25",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 69; Staff ID: 497"
  },
  {
    "username": "d.vijayan",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Deepa Vijayan",
    "department": "Nursing Department",
    "area": "Dental",
    "assignedDoctor": "",
    "joiningDate": "2024-11-07",
    "dhpLicense": "N8774",
    "qid": "538",
    "dhpExpiry": "2026-06-30",
    "category1": 34.5,
    "category23": 10.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 70; Staff ID: 538"
  },
  {
    "username": "i.mora",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ivy Mora",
    "department": "Nursing Department",
    "area": "Dental",
    "assignedDoctor": "",
    "joiningDate": "2025-11-09",
    "dhpLicense": "N31448",
    "qid": "579",
    "dhpExpiry": "2026-05-07",
    "category1": 41.5,
    "category23": 1.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 71; Staff ID: 579"
  },
  {
    "username": "a.balacuit",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Alona Elano Balacuit",
    "department": "Nursing Department",
    "area": "Dental",
    "assignedDoctor": "",
    "joiningDate": "2026-02-09",
    "dhpLicense": "N41278",
    "qid": "596",
    "dhpExpiry": "2025-11-30",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 72; Staff ID: 596"
  }
];
window.CPD_IMPORTED_STAFF = [
  {
    "username": "h.siman",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Honeylore Siman",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2018-07-08",
    "dhpLicense": "N4269",
    "qid": "46",
    "dhpExpiry": "2026-04-30",
    "category1": 49.25,
    "category23": 41.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 1; Staff ID: 46"
  },
  {
    "username": "l.ciriaco",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Luvill Ciriaco",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2018-07-08",
    "dhpLicense": "N4704",
    "qid": "47",
    "dhpExpiry": "2026-09-30",
    "category1": 32.75,
    "category23": 10.75,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 2; Staff ID: 47"
  },
  {
    "username": "g.palisoc",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Glenda Palisoc",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2018-07-15",
    "dhpLicense": "N4162",
    "qid": "54",
    "dhpExpiry": "2026-04-03",
    "category1": 40.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 3; Staff ID: 54"
  },
  {
    "username": "m.basilio",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "May Basilio",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2018-10-01",
    "dhpLicense": "N5773",
    "qid": "76",
    "dhpExpiry": "2026-06-30",
    "category1": 44.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 4; Staff ID: 76"
  },
  {
    "username": "i.edralin",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ivy Edralin",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2018-09-30",
    "dhpLicense": "N7557",
    "qid": "101",
    "dhpExpiry": "2028-02-28",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 5; Staff ID: 101"
  },
  {
    "username": "a.velasquez",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Adriene Joy Velasquez",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2019-10-06",
    "dhpLicense": "N22255",
    "qid": "192",
    "dhpExpiry": "2028-04-23",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 6; Staff ID: 192"
  },
  {
    "username": "r.guillermo",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Rejoy Guillermo",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2020-03-03",
    "dhpLicense": "N5120",
    "qid": "212",
    "dhpExpiry": null,
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 7; Staff ID: 212"
  },
  {
    "username": "m.oppus",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "May Oppus",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2020-06-16",
    "dhpLicense": "N5969",
    "qid": "230",
    "dhpExpiry": "2026-09-30",
    "category1": 41.25,
    "category23": 9.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 8; Staff ID: 230"
  },
  {
    "username": "r.guillermo2",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Rejoyce Guillermo",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2020-07-26",
    "dhpLicense": "N5038",
    "qid": "235",
    "dhpExpiry": "2027-01-14",
    "category1": 21.25,
    "category23": 9.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 9; Staff ID: 235"
  },
  {
    "username": "d.rose",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Deepa Rose",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2020-09-20",
    "dhpLicense": "N28928",
    "qid": "246",
    "dhpExpiry": "2027-02-21",
    "category1": 23.25,
    "category23": 8.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 10; Staff ID: 246"
  },
  {
    "username": "t.tom",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Teslin TOM",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2020-10-11",
    "dhpLicense": "N27522",
    "qid": "247",
    "dhpExpiry": "2026-12-31",
    "category1": 31.5,
    "category23": 37.75,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 11; Staff ID: 247"
  },
  {
    "username": "c.montes",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Cheryl Montes",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2020-10-19",
    "dhpLicense": "N7604",
    "qid": "249",
    "dhpExpiry": "2028-02-28",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 12; Staff ID: 249"
  },
  {
    "username": "m.cabrera",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Marie Grace CABRERA",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2020-11-15",
    "dhpLicense": "N16835",
    "qid": "257",
    "dhpExpiry": "2028-02-27",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 13; Staff ID: 257"
  },
  {
    "username": "k.ramirez",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Kiara Ramirez",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2020-11-22",
    "dhpLicense": "N21675",
    "qid": "259",
    "dhpExpiry": "2026-05-17",
    "category1": 42.0,
    "category23": 44.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 14; Staff ID: 259"
  },
  {
    "username": "k.englis",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Karen Mae Englis",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2020-12-12",
    "dhpLicense": "N24796",
    "qid": "264",
    "dhpExpiry": "2027-03-12",
    "category1": 12.0,
    "category23": 10.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 15; Staff ID: 264"
  },
  {
    "username": "m.marcellana",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Mishell MARCELLANA",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2020-12-26",
    "dhpLicense": "N7931",
    "qid": "266",
    "dhpExpiry": "2026-12-10",
    "category1": 41.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 16; Staff ID: 266"
  },
  {
    "username": "a.mangawang",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Agnes  Mangawang",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2021-02-21",
    "dhpLicense": "N5730",
    "qid": "280",
    "dhpExpiry": "2026-06-30",
    "category1": 31.5,
    "category23": 23.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 17; Staff ID: 280"
  },
  {
    "username": "e.sali",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Elaine A. Sali",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2021-03-14",
    "dhpLicense": "N3525",
    "qid": "286",
    "dhpExpiry": "2026-04-30",
    "category1": 40.75,
    "category23": 40.75,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 18; Staff ID: 286"
  },
  {
    "username": "m.papio",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Mary Klaudine Papio",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2021-05-17",
    "dhpLicense": "N6061",
    "qid": "291",
    "dhpExpiry": "2026-10-31",
    "category1": 40.5,
    "category23": 40.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 19; Staff ID: 291"
  },
  {
    "username": "m.nicolas",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "May Angela Nicolas",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2021-06-22",
    "dhpLicense": "N26137",
    "qid": "305",
    "dhpExpiry": "2026-07-23",
    "category1": 45.75,
    "category23": 30.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 20; Staff ID: 305"
  },
  {
    "username": "m.soriano",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Maria Soriano",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2021-08-01",
    "dhpLicense": "N4406",
    "qid": "311",
    "dhpExpiry": "2026-05-31",
    "category1": 40.0,
    "category23": 46.75,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 21; Staff ID: 311"
  },
  {
    "username": "v.ambat",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Veranica Ambat",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2021-08-01",
    "dhpLicense": "N1323",
    "qid": "312",
    "dhpExpiry": "2026-07-31",
    "category1": 43.75,
    "category23": 40.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 22; Staff ID: 312"
  },
  {
    "username": "a.abion",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ambrielle Abion",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2021-11-02",
    "dhpLicense": "N4083",
    "qid": "342",
    "dhpExpiry": "2028-03-13",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 23; Staff ID: 342"
  },
  {
    "username": "d.porquerino",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Diana Porquerino",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2021-12-07",
    "dhpLicense": "N18288",
    "qid": "356",
    "dhpExpiry": "2026-04-06",
    "category1": 40.0,
    "category23": 21.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 24; Staff ID: 356"
  },
  {
    "username": "a.casio",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Angelie Casio",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2022-01-10",
    "dhpLicense": "N25354",
    "qid": "363",
    "dhpExpiry": "2026-04-16",
    "category1": 40.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 25; Staff ID: 363"
  },
  {
    "username": "j.joseph",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Jissa Ann Joseph",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2022-02-01",
    "dhpLicense": "N23091",
    "qid": "369",
    "dhpExpiry": "2026-09-24",
    "category1": 40.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 26; Staff ID: 369"
  },
  {
    "username": "j.james",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Jasana James",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2020-03-01",
    "dhpLicense": "N5120",
    "qid": "370",
    "dhpExpiry": "2026-07-11",
    "category1": 16.75,
    "category23": 35.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 27; Staff ID: 370"
  },
  {
    "username": "l.tubon",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Lady Rosepink Tubon",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2022-05-17",
    "dhpLicense": "N17128",
    "qid": "389",
    "dhpExpiry": "2027-01-26",
    "category1": 29.0,
    "category23": 11.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 28; Staff ID: 389"
  },
  {
    "username": "n.jose",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Neethu Jose",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2022-05-22",
    "dhpLicense": "N16679",
    "qid": "383",
    "dhpExpiry": "2028-04-28",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 29; Staff ID: 383"
  },
  {
    "username": "s.naiju",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Sarika Naiju",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2022-10-04",
    "dhpLicense": "N16616",
    "qid": "404",
    "dhpExpiry": "2026-11-20",
    "category1": 39.5,
    "category23": 11.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 30; Staff ID: 404"
  },
  {
    "username": "n.jhons",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Nittu Jhons",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2022-11-27",
    "dhpLicense": "N31048",
    "qid": "411",
    "dhpExpiry": "2026-05-25",
    "category1": 41.5,
    "category23": 43.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 31; Staff ID: 411"
  },
  {
    "username": "a.pilaparambath",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Anjuna Pilaparambath",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2023-01-01",
    "dhpLicense": "N31424",
    "qid": "415",
    "dhpExpiry": "2026-03-07",
    "category1": 40.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 32; Staff ID: 415"
  },
  {
    "username": "a.mary",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ajisha Mary",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2023-01-07",
    "dhpLicense": "N32737",
    "qid": "416",
    "dhpExpiry": "2027-01-09",
    "category1": 22.5,
    "category23": 6.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 33; Staff ID: 416"
  },
  {
    "username": "c.byenconsejo",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Cheanne Byenconsejo",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2023-02-01",
    "dhpLicense": "N23995",
    "qid": "420",
    "dhpExpiry": "2026-11-11",
    "category1": 44.5,
    "category23": 41.25,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 34; Staff ID: 420"
  },
  {
    "username": "e.perez",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Emelita Manuel Perez",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2023-05-15",
    "dhpLicense": "N976",
    "qid": "452",
    "dhpExpiry": "2027-02-01",
    "category1": 10.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 35; Staff ID: 452"
  },
  {
    "username": "m.barles",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Mae Penelope Barles",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2023-11-27",
    "dhpLicense": "N36185",
    "qid": "486",
    "dhpExpiry": null,
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 36; Staff ID: 486"
  },
  {
    "username": "j.marcos",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Jasmin Romero Marcos",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2023-11-29",
    "dhpLicense": "N22083",
    "qid": "487",
    "dhpExpiry": "2026-11-05",
    "category1": 50.5,
    "category23": 40.57,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 37; Staff ID: 487"
  },
  {
    "username": "a.gana",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Arlyn Gana",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2024-06-03",
    "dhpLicense": "N28608",
    "qid": "513",
    "dhpExpiry": null,
    "category1": 6.5,
    "category23": 9.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 38; Staff ID: 513"
  },
  {
    "username": "w.reales",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Wilma Reales",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2024-12-04",
    "dhpLicense": "N3015",
    "qid": "542",
    "dhpExpiry": "2027-10-12",
    "category1": 21.5,
    "category23": 3.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 39; Staff ID: 542"
  },
  {
    "username": "j.paz",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Jimmylyn De La Paz",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2025-01-15",
    "dhpLicense": "N16566",
    "qid": "549",
    "dhpExpiry": "2027-02-14",
    "category1": 34.75,
    "category23": 34.75,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 40; Staff ID: 549"
  },
  {
    "username": "b.varghese",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Bincy Varghese",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2025-07-20",
    "dhpLicense": "N22143",
    "qid": "572",
    "dhpExpiry": "2027-07-17",
    "category1": 12.0,
    "category23": 20.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 41; Staff ID: 572"
  },
  {
    "username": "a.taher",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Abdel Rahman Taher",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2026-02-08",
    "dhpLicense": "TN143328",
    "qid": "594",
    "dhpExpiry": "2026-08-05",
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 42; Staff ID: 594"
  },
  {
    "username": "m.brisones",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Millie Anne David Brisones",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2026-02-21",
    "dhpLicense": "N35149",
    "qid": "597",
    "dhpExpiry": "2027-11-16",
    "category1": 22.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 43; Staff ID: 597"
  },
  {
    "username": "a.thomas",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Alphonsa Thomas",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2026-03-08",
    "dhpLicense": "N32608",
    "qid": "602",
    "dhpExpiry": "2026-12-21",
    "category1": 20.0,
    "category23": 2.25,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 44; Staff ID: 602"
  },
  {
    "username": "l.guzman",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Liberty Guzman",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2023-04-16",
    "dhpLicense": "",
    "qid": "440",
    "dhpExpiry": null,
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 45; Staff ID: 440"
  },
  {
    "username": "a.acob",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Arabella Acob",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2023-07-12",
    "dhpLicense": "",
    "qid": "461",
    "dhpExpiry": null,
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 46; Staff ID: 461"
  },
  {
    "username": "v.centeno",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Vener Centeno",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2025-02-23",
    "dhpLicense": "TA134809",
    "qid": "555",
    "dhpExpiry": null,
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 47; Staff ID: 555"
  },
  {
    "username": "a.najjar",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ahmad Al Najjar",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2018-07-08",
    "dhpLicense": "N9710",
    "qid": "50",
    "dhpExpiry": null,
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 48; Staff ID: 50"
  },
  {
    "username": "a.santos",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Aleha Santos",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2019-03-03",
    "dhpLicense": "N2836",
    "qid": "150",
    "dhpExpiry": "2026-10-31",
    "category1": 36.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 49; Staff ID: 150"
  },
  {
    "username": "e.castro",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Editha Castro",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2018-10-14",
    "dhpLicense": "N107",
    "qid": "105",
    "dhpExpiry": "2027-01-31",
    "category1": 43.0,
    "category23": 41.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 50; Staff ID: 105"
  },
  {
    "username": "e.benson",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Efua Benson",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2018-07-08",
    "dhpLicense": "N23402",
    "qid": "42",
    "dhpExpiry": "2026-08-15",
    "category1": 40.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 51; Staff ID: 42"
  },
  {
    "username": "f.micheal",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Felora Micheal",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2019-11-13",
    "dhpLicense": "N15395",
    "qid": "201",
    "dhpExpiry": "2026-07-17",
    "category1": 40.75,
    "category23": 41.75,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 52; Staff ID: 201"
  },
  {
    "username": "j.gadia",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Jeffrey Gadia",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2018-07-15",
    "dhpLicense": "N23950",
    "qid": "52",
    "dhpExpiry": null,
    "category1": 24.5,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 53; Staff ID: 52"
  },
  {
    "username": "c.mariam",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Christy Mariam",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2022-05-22",
    "dhpLicense": "N32423",
    "qid": "382",
    "dhpExpiry": "2026-11-23",
    "category1": 40.0,
    "category23": 9.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 54; Staff ID: 382"
  },
  {
    "username": "a.balo",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Alfred Balo",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2023-06-18",
    "dhpLicense": "N27847",
    "qid": "455",
    "dhpExpiry": "2027-06-13",
    "category1": 39.25,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 55; Staff ID: 455"
  },
  {
    "username": "r.agunat",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Rueben Agunat",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2018-07-08",
    "dhpLicense": "N23856",
    "qid": "48",
    "dhpExpiry": "2026-10-25",
    "category1": 33.0,
    "category23": 41.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 56; Staff ID: 48"
  },
  {
    "username": "b.george",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Bilga George",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2025-07-01",
    "dhpLicense": "TN137711",
    "qid": "569",
    "dhpExpiry": "2027-10-14",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 57; Staff ID: 569"
  },
  {
    "username": "a.sapii",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Arweda Sapii",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2020-11-01",
    "dhpLicense": "N17952",
    "qid": "255",
    "dhpExpiry": "2026-04-30",
    "category1": 33.0,
    "category23": 40.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 58; Staff ID: 255"
  },
  {
    "username": "v.aranez",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Virna Aranez",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2022-04-02",
    "dhpLicense": "N31096",
    "qid": "378",
    "dhpExpiry": "2026-05-30",
    "category1": 45.0,
    "category23": 60.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 59; Staff ID: 378"
  },
  {
    "username": "m.cuyno",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ma. Katrina Cuyno",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2022-11-01",
    "dhpLicense": "N23135",
    "qid": "405",
    "dhpExpiry": "2026-11-03",
    "category1": 27.5,
    "category23": 20.7,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 60; Staff ID: 405"
  },
  {
    "username": "f.casareno",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "FE Casareno",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2023-02-01",
    "dhpLicense": "N32892",
    "qid": "421",
    "dhpExpiry": "2027-01-30",
    "category1": 45.75,
    "category23": 17.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 61; Staff ID: 421"
  },
  {
    "username": "r.baby",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ruby Baby",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2025-06-01",
    "dhpLicense": "TN137446",
    "qid": "564",
    "dhpExpiry": "2027-07-22",
    "category1": 32.0,
    "category23": 9.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 62; Staff ID: 564"
  },
  {
    "username": "a.meethal",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Aswathi Kollacheri Meethal",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2026-03-09",
    "dhpLicense": "TN143793",
    "qid": "603",
    "dhpExpiry": null,
    "category1": 0,
    "category23": 0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 63; Staff ID: 603"
  },
  {
    "username": "m.escobar",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Marian Escobar",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2018-10-31",
    "dhpLicense": "A2591",
    "qid": "122",
    "dhpExpiry": "2026-12-13",
    "category1": 23.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 64; Staff ID: 122"
  },
  {
    "username": "c.fabito",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Cherrielyn Fabito",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2018-10-01",
    "dhpLicense": "N19632",
    "qid": "95",
    "dhpExpiry": "2026-11-14",
    "category1": 25.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 65; Staff ID: 95"
  },
  {
    "username": "k.andal",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Kevin Andal",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2018-10-14",
    "dhpLicense": "N24530",
    "qid": "108",
    "dhpExpiry": "2027-01-16",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 66; Staff ID: 108"
  },
  {
    "username": "c.sabandal",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Chona Sabandal",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2019-02-02",
    "dhpLicense": "N3275",
    "qid": "155",
    "dhpExpiry": "2026-08-19",
    "category1": 9.5,
    "category23": 46.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 67; Staff ID: 155"
  },
  {
    "username": "a.nocete",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Annaliza Nocete",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2021-08-01",
    "dhpLicense": "N4925",
    "qid": "310",
    "dhpExpiry": "2026-11-30",
    "category1": 28.0,
    "category23": 6.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 68; Staff ID: 310"
  },
  {
    "username": "m.echon",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Michelle Echon",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2024-02-20",
    "dhpLicense": "A22523",
    "qid": "497",
    "dhpExpiry": "2028-01-25",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 69; Staff ID: 497"
  },
  {
    "username": "d.vijayan",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Deepa Vijayan",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2024-11-07",
    "dhpLicense": "N8774",
    "qid": "538",
    "dhpExpiry": "2026-06-30",
    "category1": 34.5,
    "category23": 10.5,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 70; Staff ID: 538"
  },
  {
    "username": "i.mora",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Ivy Mora",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2025-11-09",
    "dhpLicense": "N31448",
    "qid": "579",
    "dhpExpiry": "2026-05-07",
    "category1": 41.5,
    "category23": 1.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 71; Staff ID: 579"
  },
  {
    "username": "a.balacuit",
    "password": "1234",
    "role": "staff",
    "active": true,
    "fullName": "Alona Elano Balacuit",
    "department": "Nursing Department",
    "area": "Nursing",
    "assignedDoctor": "",
    "joiningDate": "2026-02-09",
    "dhpLicense": "N41278",
    "qid": "596",
    "dhpExpiry": "2025-11-30",
    "category1": 0.0,
    "category23": 0.0,
    "email": "",
    "mobile": "",
    "notes": "Imported from Nursing License & CPD Tracking Sheet. Original No: 72; Staff ID: 596"
  }
];
window.CPD_SEED_SETTINGS = {
  targetTotal: 80,
  targetCategory1: 40,
  targetCategory23: 40,
  reminderMonthsBefore: 4,
  adminEmail: '',
  emailServiceId: '',
  emailTemplateId: '',
  emailPublicKey: ''
};
